name: Check Conventions & Design System

on:
  pull_request:
    paths:
      - 'backend/prisma/schema.prisma'
      - 'backend/src/routes/**'
      - 'frontend/src/components/**'
      - 'frontend/src/styles/tokens.css'
      - 'CONVENTIONS.md'

jobs:
  check-conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run conventions check
        run: node scripts/check-conventions.js 